site_name: Seppli's Summaries
site_author: Sebastian Zumbrunn
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
